### ISSUE TITLE
README.md doesn't say how to install or use the app

### ISSUE THREAD

**Issue by Mrigyen** [adiabatic/predictions#2]
I have zero actual experience with `golang`, and I have given up on attempting to use the application simply because I don't know how to use it. 

I tried `make` and it doesn't seem to do anything useful.

I tried `go run main.go` and it gives this error:

```
main.go:18:2: cannot find package "github.com/adiabatic/predictions/cmd" in any of:
	/usr/lib/go-1.10/src/github.com/adiabatic/predictions/cmd (from $GOROOT)
	/home/seneca/go/src/github.com/adiabatic/predictions/cmd (from $GOPATH)

```

So please update README.md. Thanks.

**Comment by adiabatic** [comment]
Thanks for the feedback. In the meantime: run `go build` and then run `./predictions`.
